name: StableDiffusionApp
options:
  bundleIdPrefix: com.ericksa
  deploymentTarget:
    macOS: "13.1"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.1"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGNING_ALLOWED: NO
    ENABLE_HARDENED_RUNTIME: NO

packages:
  StableDiffusion:
    path: ../ml-stable-diffusion

targets:
  StableDiffusionApp:
    type: application
    platform: macOS
    sources:
      - path: Sources
    resources:
      - path: Resources
        buildPhase: resources
    dependencies:
      - package: StableDiffusion
        product: StableDiffusion
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ericksa.StableDiffusionApp
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_NAME: StableDiffusionApp
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        ENABLE_HARDENED_RUNTIME: NO
        CODE_SIGN_ENTITLEMENTS: Sources/StableDiffusionApp.entitlements
